import "./globals.css";
import { Inter } from "next/font/google";
import ThemeContext from "../context/ThemeContext";
import Navbar from "@/components/Navbar";
import ReduxProvider from "@/context/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Client Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`w-full h-full ${inter.className}`}>
        <ReduxProvider>
          <ThemeContext>
            <div className="w-full h-full px-8 pt-4 pb-16">
              <Navbar />
              {children}
            </div>
          </ThemeContext>
        </ReduxProvider>
      </body>
    </html>
  );
}
